/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Client {
  address: string
  port: number
  password?: string
  expectedName?: string
  psk?: string
  clientInfo?: string
  keepAliveDuration?: number
  constructor(address: string, port: number, password?: string | undefined | null, expectedName?: string | undefined | null, psk?: string | undefined | null, clientInfo?: string | undefined | null, keepAliveDuration?: number | undefined | null)
  connect(login: boolean): Promise<void>
  deviceInfo(): Promise<DeviceInfo>
}

export declare class DeviceInfo {
  usesPassword: boolean
  name: string
  friendlyName: string
  macAddress: string
  compilationTime: string
  model: string
  manufacturer: string
  hasDeepSleep: boolean
  esphomeVersion: string
  projectName: string
  projectVersion: string
  webserverPort: number
  legacyVoiceAssistantVersion: number
  voiceAssistantFeatureFlags: number
  legacyBluetoothProxyVersion: number
  bluetoothProxyFeatureFlags: number
  suggestedArea: string
  bluetoothProxyFeatureFlagsCompat(apiVersion: ApiVersion): number
  voiceAssistantFeatureFlagsCompat(apiVersion: ApiVersion): number
}

export interface ApiVersion {
  major: number
  minor: number
}
